sudo: false
language: python
python:
  - '2.7'
  - '3.4'
env:
  global:
    - DB=postgres
  matrix:
    - DJANGO=">=1.8,<1.9"
    - DJANGO=">=1.9,<1.10"
install:
  - pip install -q coverage flake8 Django$DJANGO django-nose>=1.4
  - pip install -r requirements/docs.txt
before_script:
  - psql -c 'CREATE DATABASE manager_utils;' -U postgres
script:
  - flake8 .
  - coverage run setup.py test
  - coverage report --fail-under=100
  - python setup.py install
  - python setup.py build_sphinx
